app/raport/models.py
from app import db

class Sprzedaz(db.Model):
    __tablename__ = 'sprzedaz'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    miasto = db.Column(db.String(99), nullable=False)
    kierowca = db.Column(db.String(99), nullable=False)
    stoisko = db.Column(db.String(99), nullable=False)
    data = db.Column(db.Date, nullable=False)
    godzina = db.Column(db.String(99), nullable=False)
    towar = db.Column(db.String(99), nullable=False)
    sprzedane = db.Column(db.Integer, nullable=False)

    def __init__(self, miasto, kierowca, stoisko, data, godzina, towar, sprzedane):
    
        self.miasto = miasto 
        self.kierowca = kierowca
        self.stoisko = stoisko
        self.data = data
        self.godzina = godzina
        self.towar = towar
        self.sprzedane = sprzedane 

class Stany_wyjsciowe(db.Model):
    __tablename__ = 'stany_wyjsciowe'

    id_stoiska = db.Column(db.Integer, primary_key=True)
    miasto = db.Column(db.String(99), nullable=False)
    stoisko = db.Column(db.String(99), nullable=False)
    data = db.Column(db.Date, nullable=False)
    towar = db.Column(db.String(99), nullable=False)
    stan_wyjsciowy = db.Column(db.Integer, nullable=False)

    def __init__(self, miasto, stoisko, data,  towar, stan_wyjsciowy):
        self.miasto = miasto 
        self.stoisko = stoisko
        self.data = data
        self.towar = towar
        self.stan_wyjsciowy = stan_wyjsciowy 

class Stoiska(db.Model):
    __tablename__ = 'stoiska'

    id = db.Column(db.Integer, primary_key=True)
    miasto = db.Column(db.String(99), nullable=False)
    stoisko = db.Column(db.String(99), nullable=False)
    lat = db.Column(db.Float, nullable=False)
    lon = db.Column(db.Float, nullable=False)
    

    def __init__(self, miasto, stoisko, lat,  lon):
        self.miasto = miasto 
        self.stoisko = stoisko
        self.lat = lat
        self.lon = lon

app/raport/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, RadioField
from wtforms.validators import DataRequired

class SendRaportForm(FlaskForm):
    def __init__(self, stoiska_kierowcy):
        super().__init__()
        self.stoisko_k.choices = [(x.stoisko, x.stoisko) for x in stoiska_kierowcy]

    godzina = RadioField('Godzina', choices=['12','14','16'])
    
    stoisko_k = RadioField('Stoisko')
    sprzedane_roze = IntegerField('Sprzedane róże: ',validators=[DataRequired()])
    sprzedane_tulipany = IntegerField('Sprzedane tulipany: ',validators=[DataRequired()])
    submit = SubmitField('Wyślij')

app/raport/__init__.py
#app/raport/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates')

from app.raport import routes

app/raport/routes.py
from app.raport import main
from app import db
from app.raport.forms import SendRaportForm
from app.raport.models import Sprzedaz, Stany_wyjsciowe, Stoiska
from app.auth.models import Kierowca
from flask import render_template, request, redirect, url_for, flash, session
from flask_login import current_user, login_required
from datetime import datetime




@main.route('/wyslij', methods=['GET','POST'])
@login_required
def wyslij():
    stany_wyjsciowe = Stany_wyjsciowe.query.all()
    today = datetime.today().strftime('%d-%m-%Y')
    miasto_kierowcy = Kierowca.query.filter_by(user_name=session['username']).first().user_city
    stoiska_kierowcy = Stoiska.query.filter_by(miasto=miasto_kierowcy).all()
    form = SendRaportForm(stoiska_kierowcy)
    if form.validate_on_submit():
        sprzedaz_r = Sprzedaz(miasto=miasto_kierowcy, kierowca=session['username'], stoisko=form.stoisko_k.data,data=today, godzina=form.godzina.data, towar='róże',sprzedane=form.sprzedane_roze.data)
        sprzedaz_t = Sprzedaz(miasto=miasto_kierowcy, kierowca=session['username'], stoisko=form.stoisko_k.data,data=today, godzina=form.godzina.data, towar='tulipany',sprzedane=form.sprzedane_tulipany.data)
        db.session.add_all([sprzedaz_r,sprzedaz_t])
        db.session.commit()
        return redirect(url_for("main.raport_wyslany"))

    return render_template('wyslij.html', form=form, stany_wyjsciowe=stany_wyjsciowe,miasto_kierowcy=miasto_kierowcy,stoiska_kierowcy=stoiska_kierowcy)

@main.route('/', methods=['GET','POST'])
def index():

    return render_template('index.html')

@main.route('/raport_wyslany')
def raport_wyslany():

    return render_template('raport_wyslany.html')

app/raport/templates/index.html
{% extends 'layout.html' %}

app/raport/templates/layout.html
{% import "bootstrap/wtf.html" as wtf %}

<html lang="en">

    {# head #}
    {% block head %}
        <head>
            <title> Berry </title>
            <meta charset="UTF-8">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            <link href="https://fonts.googleapis.com/css?family=Sansita" rel="stylesheet">
            <link rel="stylesheet" type= "text/css" href="{{ url_for('static', filename='css/styles.css') }}">
            <link rel="stylesheet" type= "text/css" href="{{ url_for('static',filename='styles/mainpage.css') }}">
        </head>
    {% endblock head %}

    {# body #}
    {% block body %}
    <body>
    <div class="wrapper">
        {# navigation bar #}
        {% block navbar %}
        <nav class="navbar navbar-inverse">
            <div class="container">
                <a class="navbar-brand title" href="{{ url_for('main.wyslij') }}">Raporty dzienne</a>

                <ul class="nav navbar-nav pull-right nav-list">
                    <li><a href="{{ url_for('main.index')}}"> Home </a></li>
                    <li>
                        {% if current_user.is_authenticated %}
                            <a href="{{ url_for('authentication.log_out_user')}}"> Wyloguj </a>
                        {% else %}
                            <a href="{{ url_for('authentication.do_the_login')}}"> Zaloguj </a>
                        {% endif %}
                    </li>

                    <li>
                        <a>
                            {% if current_user.is_authenticated %}
                                Ceść <b style="color: deepink">{{ current_user.user_name.title() }}</b>
                            {% else %}
                                Nie jesteś zalogowany
                            {% endif %}
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        {% endblock navbar %}

        {# flash messaging #}
        {% for message in get_flashed_messages() %}
            <div class="container alert alert-info">
                <button type="button" class="close" data-dismiss="alert"></button>
                {{ message }}
            </div>
        {% endfor %}

        {# empty block for custom content #}
        {% block content %} {% endblock content %}

        {# footer #}
        {% block footer %}
        <footer>
            <div class="container ftr">
                <hr>
                <p class="text-center small"> Berry &copy;	| 2022 </p>
            </div>
        </footer>
        {% endblock footer %}

    </div>
    </body>
    {% endblock body %}
</html>

app/raport/templates/raport_wyslany.html
{% extends 'layout.html' %}

{% block content %}
<h1>Dzięki za wysłanie raportu!</h1>
<!-- <h2>Sprzedałeś: {{session['tulipany']}} tulipanów</h2>
<h2>Sprzedałeś: {{session['roze']}} róż</h2> -->
{% endblock content %}

app/raport/templates/wyslij.html
{% extends 'layout.html' %}


{% block content %}

    <div>
        <h3>Stan wyjściowy to:</h3>
        {% for s in stany_wyjsciowe %}
            <p>{{ s.stan_wyjsciowy }} sztuk {{ s.towar }} na stoisku {{s.stoisko}}</p>
        {% endfor %}

    </div>
<!--
    <div>
        <h3>Stoiska to:</h3>
        {% for s in stoiska_kierowcy %}
            <p>{{s.stoisko}}</p>
        {% endfor %}

    </div>
-->
    <div>
        <form method="POST">
            {{form.hidden_tag()}}

            {{form.stoisko_k.label}}
            <br>
            {% for subfield in form.stoisko_k %}
            <tr>
                <td>{{ subfield }}</td>
                <td>{{ subfield.label }}</td>
            </tr>
            {% endfor %}
            <br>

            {{form.godzina.label}}
            <br>
            {% for subfield in form.godzina %}
            <tr>
                <td>{{ subfield }}</td>
                <td>{{ subfield.label }}</td>
            </tr>
            {% endfor %}
            <br>
            {{form.sprzedane_tulipany.label}}{{form.sprzedane_tulipany}}
            <br>
            {{form.sprzedane_roze.label}}{{form.sprzedane_roze}}
            <br>
            {{form.submit()}}
        </form>
    </div>

{% endblock content %}